server:
  context-path: /userauth
  port: 8899

#spring:
#  data:
#    mongodb:
#      host: 192.168.0.126
#      port: 27017
#      database: oauth
#      username: cd2
#      password: cd2
#  jackson:
#    property-naming-strategy: SNAKE_CASE

spring:
  data:
    mongodb:
      host: 52.57.210.172
      port: 27017
      database: aucobo
      username: aucoborw
      password: yemnofomm0!blub
      authentication-database: admin
      repositories:
        enabled: true

logging:
 level:
  org.springframework.security: DEBUG
