server:
  context-path: /userauth
  port: 8899

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: oauth
      username: cd2
      password: cd2
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
 level:
  org.springframework.security: DEBUG
