version: '2.1'
services:
#  mongodb:
#        image: mongo:latest
#        container_name: "mongodb"
#        environment:
#          - MONGO_DATA_DIR=/data/db
#          - MONGO_LOG_DIR=/dev/null
#          - MONGODB_USER="cd2"
#          - MONGODB_PASS="cd2"
#          - MONGODB_DATABASE=oauth
#        volumes:
#          - ./data/db:/data/db
#        ports:
#            - 27017:27017
#        command: mongod --smallfiles --logpath=/dev/null # --quiet


  configserver:
    image: config-server
    mem_limit: 1073741824
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-I", "http://configserver:8888"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "8888/tcp"
#    depends_on:
#      mysqldb:
#        condition: service_healthy

  eurekaregistry:
    image: webservice-registry
    mem_limit: 1073741824
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eurekaregistry:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "8761:8761/tcp"
    depends_on:
      configserver:
        condition: service_healthy

  authserver:
    image: auth-server
    mem_limit: 1073741824
    restart: unless-stopped
    ports:
      - "8899/tcp"
    depends_on:
      eurekaregistry:
        condition: service_healthy

  apigateway:
    image: api-gateway
    mem_limit: 1073741824
    restart: unless-stopped
    ports:
      - "8765:8765/tcp"
    depends_on:
      eurekaregistry:
        condition: service_healthy

  zipkinserver:
    image: zipkin-server
    mem_limit: 1073741824
    restart: unless-stopped
    ports:
      - "9411:9411/tcp"
    depends_on:
      configserver:
        condition: service_healthy
